version: '3.8'
services:
  web:
    build: .
    restart: always
    environment:
      WAIT_HOSTS: es:9200
    ports:
      - "8080:${PORT}"
    env_file: .env
    depends_on:
      - es
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "10"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: es
    extra_hosts:
      - "es:127.0.0.1"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300